import { useState } from 'react';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db, auth } from '../firebase';
import { GoogleGenAI } from '@google/genai';

// Helper to convert File to base64
const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => {
            const base64 = reader.result.split(',')[1];
            resolve(base64);
        };
        reader.onerror = reject;
        reader.readAsDataURL(file);
    });
};

export default function UploadSection() {
    const [file, setFile] = useState(null);
    const [stage, setStage] = useState('idea');

    // UI State
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [currentCardIndex, setCurrentCardIndex] = useState(0);

    // AI Data State
    const [aiResponse, setAiResponse] = useState(null);

    const handleFileChange = (e) => {
        if (e.target.files.length > 0) {
            setFile(e.target.files[0]);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!file) {
            alert("Please select a file first!");
            return;
        }

        setIsAnalyzing(true);

        try {
            // Initialize Gemini SDK
            const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY });

            // Prepare the image
            const base64Data = await fileToBase64(file);

            // The brutal prompt
            const prompt = `You are a brutal, savage tech critic called 'Verdict AI'. The user has uploaded a file of their software project at the '${stage}' stage.
Analyze it and generate a harsh but constructive roast. 
You MUST respond with ONLY a valid JSON array containing exactly 4 objects. Do not wrap it in markdown code blocks.
The 4 objects must have the following 'id's: 'overview', 'feedback', 'competitors', 'roastcard'.
Each object must have these keys: 'id', 'category', 'title', 'tagline', 'contentHTML'.
'contentHTML' must be formatted as raw HTML (e.g. <p>, <strong>, <ul>, <li>) that will be injected directly into a React dashboard.
The 'overview' object must ALSO contain a numerical 'score' key out of 10.

Example array structure:
[
  { "id": "overview", "category": "Overview & Scores", "title": "Project: [Name]", "tagline": "[Savage quote]", "contentHTML": "<p><strong>Design:</strong> 4/10 - My eyes bleed.</p>", "score": 4 },
  { "id": "feedback", "category": "Brutal Feedback", "title": "What is Wrong", "tagline": "Time for the roast", "contentHTML": "<ul><li>Too many links</li></ul>" },
  { "id": "competitors", "category": "Market & Competitors", "title": "How to Stand Out", "tagline": "You are not alone", "contentHTML": "<p>Competitor X will crush you.</p>" },
  { "id": "roastcard", "category": "RoastCard", "title": "The Roast Card", "tagline": "Get roasted", "contentHTML": "<p>Skill issues.</p>" }
]`;

            // Call the AI
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: [
                    prompt,
                    { inlineData: { data: base64Data, mimeType: file.type } }
                ]
            });

            // Parse the JSON
            const jsonText = response.text.replace(/```json/g, '').replace(/```/g, '').trim();
            const parsedResponse = JSON.parse(jsonText);

            setAiResponse(parsedResponse);
            setIsSubmitted(true);
            setCurrentCardIndex(0);

        } catch (error) {
            console.error("AI Error:", error);
            alert("Failed to analyze project: " + error.message);
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handlePublishToCommunity = async () => {
        if (!auth.currentUser) {
            alert("You must be logged in to publish to the community!");
            return;
        }

        try {
            // Find the global score generated by Gemini
            const overviewCard = aiResponse.find(card => card.id === 'overview');
            const finalScore = overviewCard?.score || 5;

            await addDoc(collection(db, 'posts'), {
                author: auth.currentUser.displayName || auth.currentUser.email,
                projectName: file.name,
                content: "I just uploaded this project for an AI roast. Here is the verdict!",
                stage: stage,
                score: finalScore,
                roastSnippet: `Verdict AI: '${overviewCard?.tagline}'`,
                reactions: 0,
                hasReacted: false,
                comments: 0,
                date: new Date().toLocaleDateString(),
                createdAt: serverTimestamp()
            });
            alert("Successfully published to the Community Feed!");
        } catch (error) {
            console.error("Error publishing:", error);
            alert("Failed to publish.");
        }
    };

    return (
        <div style={{ padding: '4rem 2rem', borderTop: '1px solid gray', marginTop: '2rem' }}>

            <h2>Upload for AI Criticism</h2>
            <p>Select your file and tell us what stage your project is currently in.</p>

            {/* LOADING STATE OVERRIDE */}
            {isAnalyzing && (
                <div style={{ textAlign: 'center', padding: '3rem', backgroundColor: '#111', borderRadius: '12px', border: '1px solid #ff005dff' }}>
                    <h2 style={{ color: '#00ffc8' }}>🧠 The AI is Judging You...</h2>
                    <p style={{ color: 'gray' }}>Analyzing pixels, reading code, and formulating brutal feedback. Please wait.</p>
                </div>
            )}

            {!isSubmitted && !isAnalyzing && (
                <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxWidth: '400px' }}>
                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem' }}>Project File (Image/Code/PDF):</label>
                        <input type="file" onChange={handleFileChange} />
                    </div>

                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem' }}>Project Stage:</label>
                        <select value={stage} onChange={(e) => setStage(e.target.value)} style={{ padding: '0.5rem', width: '100%' }}>
                            <option value="idea">Just an Idea / Concept</option>
                            <option value="ui">UI/UX Design Mockup</option>
                            <option value="mvp">Minimum Viable Product (MVP)</option>
                            <option value="live">Live Product</option>
                        </select>
                    </div>

                    <button type="submit" style={{ padding: '0.75rem', cursor: 'pointer', fontWeight: 'bold' }}>
                        Submit for AI Criticism
                    </button>
                </form>
            )}

            {isSubmitted && !isAnalyzing && aiResponse && (
                <div className="results-dashboard" style={{ marginTop: '2rem', border: '1px solid #ccc', padding: '1rem' }}>

                    {/* Mini-Navbar */}
                    <div style={{ display: 'flex', gap: '1rem', borderBottom: '1px solid #ccc', paddingBottom: '1rem', marginBottom: '1rem' }}>
                        {aiResponse.map((card, index) => (
                            <button
                                key={card.id}
                                onClick={() => setCurrentCardIndex(index)}
                                style={{
                                    fontWeight: currentCardIndex === index ? 'bold' : 'normal',
                                    color: currentCardIndex === index ? 'red' : 'black',
                                    cursor: 'pointer'
                                }}
                            >
                                {card.category}
                            </button>
                        ))}
                    </div>

                    {/* Active Card */}
                    <div className="active-card" style={{ padding: '1rem', backgroundColor: '#f9f9f9', color: '#000', minHeight: '200px', borderRadius: '8px' }}>
                        <h2>{aiResponse[currentCardIndex].title}</h2>
                        <h4 style={{ fontStyle: 'italic', color: '#555' }}>{aiResponse[currentCardIndex].tagline}</h4>

                        {/* Render HTML Safely from Gemini */}
                        <div
                            style={{ marginTop: '1rem' }}
                            dangerouslySetInnerHTML={{ __html: aiResponse[currentCardIndex].contentHTML }}
                        />
                    </div>

                    {/* Navigation Buttons */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '1rem' }}>
                        <button disabled={currentCardIndex === 0} onClick={() => setCurrentCardIndex(currentCardIndex - 1)}>
                            ← Previous
                        </button>
                        <button disabled={currentCardIndex === aiResponse.length - 1} onClick={() => setCurrentCardIndex(currentCardIndex + 1)}>
                            Next →
                        </button>
                    </div>

                    <button
                        onClick={handlePublishToCommunity}
                        style={{ display: 'block', marginTop: '3rem', width: '100%', padding: '1rem', backgroundColor: '#00ffc8', color: 'black', fontWeight: 'bold', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '1.2rem' }}
                    >
                        Publish Roast to Community 🌎
                    </button>

                    <button
                        onClick={() => setIsSubmitted(false)}
                        style={{ display: 'block', marginTop: '2rem', width: '100%', padding: '0.5rem' }}
                    >
                        Start Over (Upload Another)
                    </button>
                </div>
            )}
        </div>
    );
}
